version: "3.7"
services:
        db: 
                image: tamarabarbosa/gece-postgres-db:latest
                restart: always
                ports:
                        - "5432:5432"
                volumes:
                        - ./appgces-db:/var/lib/postgresql/data
        nginx:
                build:
                        context: ./
                        dockerfile: ./Dockerfile.nginx
                ports:
                        - '8020:8020'
        app:
                build:
                        context: ./
                        args:
                                USER_ID: "${USER_ID:-1000}"
                                GROUP_ID: "${GROUP_ID:-1000}"
                container_name: gces-aplicacao
                volumes:
                        - ./appgces-aplicacao:/opt/app
                ports:
                        - "3000:3000"
                depends_on:
                        - db
                        - nginx


